#!/bin/sh
cat >/usr/lib/os-release <<'OS'
NAME="EnigmaOS"
PRETTY_NAME="EnigmaOS"
ID=enigmaos
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://enigmaos.rishispace.dev/"
DOCUMENTATION_URL="https://enigmaos.rishispace.dev/docs/"
SUPPORT_URL="https://github.com/RishiSpace/EnigmaOS/issues"
BUG_REPORT_URL="https://github.com/RishiSpace/EnigmaOS/issues"
PRIVACY_POLICY_URL="https://enigmaos.rishispace.dev/privacy"
LOGO=enigmaos
OS
rm -f /etc/os-release; cp -f /usr/lib/os-release /etc/os-release
cat >/etc/motd <<'MOTD'
Welcome to EnigmaOS

  Privacy first · Secure by default · Ready immediately

  Docs:     https://enigmaos.rishispace.dev/docs
  Issues:   https://github.com/RishiSpace/EnigmaOS/issues

  Live tip: open "Install EnigmaOS" or run:  sudo calamares

MOTD
printf 'EnigmaOS \\r (\\l)\n\n' >/etc/issue
echo enigmaos >/etc/hostname
