title    EnigmarsOS
sort-key 01
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-enigmarsos
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-enigmarsos.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID%
