title    EnigmarsOS (speech)
sort-key 02
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-enigmarsos-lts
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-enigmarsos-lts.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% accessibility=on modprobe.blacklist=nouveau nvidia-drm.modeset=1 nvidia-drm.fbdev=1
