---
efiSystemPartition:         "/boot/efi"
efiSystemPartitionSize:     512M
efiSystemPartitionName:     EFI
userSwapChoices:
    - none
    - small
    - suspend
    - file
initialSwapChoice:          small
defaultFileSystemType:      "btrfs"
availableFileSystemTypes:   ["btrfs","ext4","xfs"]
luksGeneration:             luks2
drawNestedPartitions:       true
alwaysShowPartitionLabels:  true
allowManualPartitioning:    true
initialPartitioningChoice:  always
initialSwapChoice:          small
essentialMounts:            ["/", "/boot", "/boot/efi"]
