---
services:
  - name: NetworkManager
    mandatory: true
  - name: bluetooth
    mandatory: false
  - name: ufw
    mandatory: true
  - name: apparmor
    mandatory: true
  - name: fwupd
    mandatory: false
  - name: fstrim.timer
    mandatory: false
  - name: systemd-timesyncd
    mandatory: true
  - name: cups
    mandatory: false
  - name: sddm
    mandatory: true
  - name: avahi-daemon
    mandatory: false
targets:
  - name: graphical
    mandatory: true
