---
defaultGroups:
    - users
    - wheel
    - audio
    - video
    - storage
    - optical
    - network
    - rfkill
    - sys
    - input
    - lp
    - docker
    - libvirt
autologinGroup:  autologin
doAutologin:     false
sudoersGroup:    wheel
setRootPassword: true
doReusePassword: true
availableShells: /bin/zsh, /bin/bash
avatarFilePath:  ~/.face
userShell:       /bin/zsh
passwordRequirements:
    minLength:   6
    maxLength:   0
allowWeakPasswords: true
allowWeakPasswordsDefault: true
