#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
echo "EnigmarsOS tree check"
test -f "${ROOT}/profiledef.sh"
test -f "${ROOT}/packages.x86_64"
test -f "${ROOT}/public/EnigmarsOS.png"
test -f "${ROOT}/themes/icons/EnigmarsOS/index.theme"
test -f "${ROOT}/themes/icons/EnigmarsOS/scalable/apps/start-here-kde.svg"
test -f "${ROOT}/archiso/airootfs/etc/pacman.d/hooks/enigmarsos-os-release.hook"
test -f "${ROOT}/archiso/airootfs/usr/share/libalpm/scripts/enigmarsos-os-release"
test -f "${ROOT}/packages/enigmarsos-welcome/enigmarsos-welcome"
test -f "${ROOT}/scripts/build/docker-build-iso.sh"
test -f "${ROOT}/scripts/build/fetch-kernel-repo.sh"
test -f "${ROOT}/docker/Dockerfile"
test -f "${ROOT}/archiso/airootfs/etc/pacman.d/linux-enigmarsos.conf"
grep -q '^linux-enigmarsos$' "${ROOT}/packages.x86_64"
grep -q '^enigmars-utils$' "${ROOT}/packages.x86_64"
test -f "${ROOT}/scripts/build/build-enigmars-utils-pkg.sh"
test -f "${ROOT}/archiso/airootfs/usr/local/bin/enigmars-util-autostart"
test -f "${ROOT}/archiso/airootfs/etc/skel/Desktop/org.enigmars.Util.desktop"
test -f "${ROOT}/archiso/airootfs/etc/skel/.config/autostart/org.enigmars.Util.desktop"
grep -q 'linux-enigmarsos' "${ROOT}/archiso/pacman.conf"
grep -q 'releases/latest/download' "${ROOT}/archiso/airootfs/etc/pacman.d/linux-enigmarsos.conf"
# Identity branding must target rishispace
grep -q 'enigmarsos.rishispace.dev' "${ROOT}/archiso/airootfs/usr/share/libalpm/scripts/enigmarsos-os-release"
grep -q 'rishi@rishispace.dev' "${ROOT}/packages/enigmarsos-filesystem/PKGBUILD" || true
echo "OK: basic structure intact"
