#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
echo "EnigmarsOS tree check"
test -f "${ROOT}/profiledef.sh"
test -f "${ROOT}/packages.x86_64"
test -f "${ROOT}/public/EnigmarsOS.png"
test -f "${ROOT}/themes/icons/EnigmarsOS/index.theme"
test -f "${ROOT}/themes/icons/EnigmarsOS/scalable/apps/start-here-kde.svg"
test -f "${ROOT}/archiso/airootfs/etc/pacman.d/hooks/00-enigmarsos-os-release.hook"
test -f "${ROOT}/archiso/airootfs/usr/share/libalpm/scripts/enigmarsos-os-release"
test ! -e "${ROOT}/archiso/airootfs/usr/local/bin/enigmarsos-welcome"
test ! -e "${ROOT}/archiso/airootfs/etc/xdg/autostart/enigmarsos-welcome.desktop"
test -f "${ROOT}/scripts/build/docker-build-iso.sh"
test -f "${ROOT}/scripts/build/fetch-kernel-repo.sh"
test -f "${ROOT}/scripts/build/fetch-extras-repo.sh"
test -f "${ROOT}/docker/Dockerfile"
test -f "${ROOT}/archiso/airootfs/etc/pacman.d/linux-enigmarsos.conf"
test -f "${ROOT}/archiso/airootfs/etc/pacman.d/enigmars-extras.conf"
grep -q '^linux-enigmarsos$' "${ROOT}/packages.x86_64"
grep -q '^enigmars-utils$' "${ROOT}/packages.x86_64"
test -f "${ROOT}/scripts/build/build-enigmars-utils-pkg.sh"
test -f "${ROOT}/archiso/airootfs/usr/local/bin/enigmars-util-autostart"
test -f "${ROOT}/archiso/airootfs/usr/share/enigmarsos/scripts/enigmarsos-nvidia-setup.sh"
test -f "${ROOT}/archiso/airootfs/usr/share/libalpm/scripts/enigmarsos-nvidia-dkms"
test -f "${ROOT}/archiso/airootfs/etc/pacman.d/hooks/zz-enigmarsos-nvidia-dkms.hook"
test -f "${ROOT}/archiso/airootfs/etc/enigmarsos/iso-build"
grep -q 'iso-build' "${ROOT}/archiso/airootfs/usr/share/libalpm/scripts/enigmarsos-sync-esp"
grep -q 'iso_has_enigmarsos_nvidia' "${ROOT}/docker/entrypoint.sh"
grep -q '^nvidia-open-dkms$' "${ROOT}/packages.x86_64"
test -f "${ROOT}/archiso/airootfs/etc/systemd/system/enigmarsos-nvidia-live.service"
test -f "${ROOT}/archiso/airootfs/etc/skel/Desktop/org.enigmars.Util.desktop"
test -f "${ROOT}/themes/plasma/color-schemes/EnigmarsOS.colors"
test -f "${ROOT}/themes/wallpapers/EnigmarsOS/metadata.json"
test -f "${ROOT}/wallpapers/enigmarsos-amoled.png"
test -f "${ROOT}/archiso/airootfs/usr/local/bin/enigmarsos-plasma-defaults"
grep -q 'LookAndFeelPackage=org.enigmarsos.desktop' "${ROOT}/archiso/airootfs/etc/xdg/kdeglobals"
test -f "${ROOT}/archiso/airootfs/etc/skel/.config/autostart/org.enigmars.Util.desktop"
grep -q 'linux-enigmarsos' "${ROOT}/archiso/pacman.conf"
grep -q 'enigmars-extras' "${ROOT}/archiso/pacman.conf"
grep -q 'releases/latest/download' "${ROOT}/archiso/airootfs/etc/pacman.d/linux-enigmarsos.conf"
grep -q 'releases/latest/download' "${ROOT}/archiso/airootfs/etc/pacman.d/enigmars-extras.conf"
grep -q 'enigmars-extras.conf' "${ROOT}/archiso/airootfs/etc/pacman.conf"
# Identity branding must target rishispace
grep -q 'enigmarsos.rishispace.dev' "${ROOT}/archiso/airootfs/usr/share/libalpm/scripts/enigmarsos-os-release"
grep -q 'rishi@rishispace.dev' "${ROOT}/packages/enigmarsos-filesystem/PKGBUILD" || true
echo "OK: basic structure intact"
